//
//  HistoricalEvents.swift
//  Bout TIme
//
//  Created by Tanveer Momin on 12/7/16.
//  Copyright © 2016 Tanveer Momin. All rights reserved.
//



struct HistoricalEvents {
    let events: [[String : String]] = [
        ["Year": "1900",
         "Event": "The first Zeppelin is designed by Theodor Kober.",
         "Link": "https://en.wikipedia.org/wiki/Theodor_Kober"],
        ["Year": "1904",
         "Event": "The Fleming valve, the first vacuum tube and diode, is invented by John Ambrose Fleming.",
         "Link": "https://en.wikipedia.org/wiki/Tour_de_France"],
        ["Year": "1909",
         "Event": "The first instantaneous transmission of images, or television broadcast, is carried out by Georges Rignoux and A. Fournier.",
         "Link": "https://en.wikipedia.org/wiki/Television"],
        ["Year": "1911",
         "Event": "The cloud chamber, the first particle detector, is invented by Charles Thomson Rees Wilson.",
         "Link": "https://en.wikipedia.org/wiki/Cloud_chamber"],
        ["Year": "1915",
         "Event": "The tank is invented by Ernest Swinton.",
         "Link": "https://en.wikipedia.org/wiki/Ernest_Swinton"],
        ["Year": "1927",
         "Event": "The Quartz clock is invented by Warren Marrison and J.W. Horton at Bell Telephone Laboratories.",
         "Link": "https://en.wikipedia.org/wiki/Quartz_clock"],
        ["Year": "1930",
         "Event": "The Phase-contrast microscopy is invented by Frits Zernike.",
         "Link": "https://en.wikipedia.org/wiki/Phase-contrast_microscopy"],
        ["Year": "1931",
         "Event": "The electron microscope is invented by Ernst Ruska.",
         "Link": "https://en.wikipedia.org/wiki/Electron_microscope"],
        ["Year": "1933",
         "Event": "FM radio is patented by inventor Edwin H. Armstrong.",
         "Link": "https://en.wikipedia.org/wiki/FM_broadcasting"],
        ["Year": "1942",
         "Event": "The V-2 rocket, the world's first long range ballistic missile, developed in Nazi Germany during World War II.",
         "Link": "https://en.wikipedia.org/wiki/V-2_rocket"],
        ["Year": "1944",
         "Event": "Scottish Engineer John Logie Baird developed the first color picture tube",
         "Link": "https://en.wikipedia.org/wiki/Color_television"],
        ["Year": "1947",
         "Event": "Holography is invented by Dennis Gabor.",
         "Link": "https://en.wikipedia.org/wiki/Holography"],
        ["Year": "1948",
         "Event": "The first atomic clock is developed at the United States's National Bureau of Standards.",
         "Link": "https://en.wikipedia.org/wiki/Atomic_clock"],
        ["Year": "1951",
         "Event": "First use of nuclear power to produce electricity for households in Arco, Idaho.",
         "Link": "https://en.wikipedia.org/wiki/Nuclear_power"],
        ["Year": "1952",
         "Event": "The first Thermonuclear weapon is developed by the United States of America.",
         "Link": "https://en.wikipedia.org/wiki/Thermonuclear_weapon"],
        ["Year": "1957",
         "Event": "The first PC used by one person and controlled by a keyboard, the IBM 610 is invented in 1957 by IBM.",
         "Link": "https://en.wikipedia.org/wiki/History_of_personal_computers#The_beginnings_of_the_personal_computer_industry"],
        ["Year": "1958",
         "Event": "Co-creation of the integrated circuit by Jack Kilby and Robert Noyce.",
         "Link": "https://en.wikipedia.org/wiki/Integrated_circuit"],
        ["Year": "1960",
         "Event": "The first functioning laser is invented by Theodore Maiman.",
         "Link": "https://en.wikipedia.org/wiki/Laser"],
        ["Year": "1963",
         "Event": "First home Videocassette recorder (VCR)",
         "Link": "https://en.wikipedia.org/wiki/Videocassette_recorder"],
        ["Year": "1969",
         "Event": "Unix is invented.",
         "Link": "https://en.wikipedia.org/wiki/History_of_Unix"],
        ["Year": "1970",
         "Event": "The pocket calculator is invented in Japan.",
         "Link": "https://en.wikipedia.org/wiki/Calculator#Pocket_calculators"],
        ["Year": "1971",
         "Event": "Email is invented by Ray Tomlinson.",
         "Link": "https://en.wikipedia.org/wiki/Email"],
        ["Year": "1972",
         "Event": "The first video game console, used primarily for playing video games on a TV, is the Magnavox Odyssey.",
         "Link": "https://en.wikipedia.org/wiki/Magnavox_Odyssey"],
        ["Year": "1975",
         "Event": "Altair 8800 is the spark that ignited the microcomputer revolution.",
         "Link": "https://en.wikipedia.org/wiki/Altair_8800"],
        ["Year": "1980",
         "Event": "Flash memory (both NOR and NAND types) is invented",
         "Link": "https://en.wikipedia.org/wiki/Flash_memory"]
    ]
}
